# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aliomx
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: estadistica
# "service" is the name of this project. This will also be added to your AWS resource names.
service: estadistica

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

functions:
  api:
    handler: handler.handler
    role: arn:aws:iam::591057945430:role/LabRole
    events:
      - httpApi: "*"